### ISSUE TITLE
v1.0.3 MacのシェルかWindowsでのコマンドプロンプトへの対応要望

### ISSUE THREAD

**Issue by mintiatian** [SpriteStudio/Ss5ConverterToSSAJSON#4]
GitやSVNにて登録されたプロジェクトをJenkinsにてJsonへコンバートを行いたいなと
考えているのですがMacのシェルかWindowsでのコマンドプロンプトへの対応を
していただけないでしょうか？

作成するアニメーションが多いので対応していただけますと非常にありがたいです。

**Comment by DKAlpha** [comment]
お問い合わせありがとうございます。
Ss5ConverterToSSAJSONコンバータのバッチ処理についてですが、提供しておりますWindowsのコンバータでもバッチ処理が可能ですのでご案内いたします。

概要からご説明しますと、jsonを作成するまでに２つの手順（2回のコンバート）が必要となります。
まずSpriteStudioのプロジェクトファイルであるsspjからSS5Playerで使用する汎用バイナリ形式ssbpへのコンバートと、作成したsspbを再生し各パーツのパラメータをjsonへ出力するコンバートになります。
・sspjからssbpへのコンバート方法
コンバータに含まれる「Ss5Converter.exe」がsspjをssbpにコンバートする実行ファイルになります。
引数はsspjへのパスになり、成功するとsspjのあるフォルダにssbpファイルが生成されます。
・実行例
Ss5Converter.exe c:\temp\anime.sspj

・ssbpからjsonへのコンバート方法
コンバータに含まれる「ssbpToJson.exe」がssbpをjsonへコンバートする実行ファイルになります。
引数は順番が決まっており省略する事はできません。
・引数
第１引数：ssbpファイルのパス
コンバートしたssbpファイルのパスを指定します
第２引数：インスタンス、エフェクトを展開するか？
yes固定（noにした場合の挙動は未対応です）
第３引数：パーツが基準枠の外にあるときは出力しない
yes、no
第４引数：１モーションを１ファイルで出力する
yes、no
第５引数：カラーラベル、カラーブレンド、スプライトの頂点情報を出力する
yes、no
第６引数：出力フォルダを指定する（省略可）
出力フォルダのパスを付加する（最後は必ず\にする）
パスがない場合はssbpのフォルダにjsonを出力します

・実行例
全てチェックが入った状態でC:\temp\outにjsonを出力する
ssbpToJson.exe "c:/temp/anime.sspb" yes yes yes yes "C:/temp/out/"

お手数ではございますが、動作の方ご確認いただければと思います。
よろしくお願いいたします。

※情報修正しました。
・第4引数が２つあったため修正しました。
・パスの記述を\ではなく/としました。
・ファイルのパスを"で囲みました。
ご迷惑をおかけしてすみません。

**Comment by mintiatian** [comment]
素早いご回答ありがとうございます。

一緒に同封されていましたSampleで試してみました。
Ss5Converter.exeでssbpファイルを作成するところまでは変換ができたのですが
ssbpToJson.exeにてssbpからjsonに変換する処理にてcmdにてconvert start!とでたところで
「ssbpToJson.exe は動作を停止しました」とダイアログが表示されjsonへの変換が行えません。
設定になにか見落としがあるかもしれませんが原因わかりましたらご教授いただけますと幸いです。

//----------------------------------------------------------------------
ssbpToJson.exe animetest.ssbp yes yes yes yes yes c:\temp\
Ss5Converter To SSAJSON Version=1.0.2
convert start!
この後「ssbpToJson.exe は動作を停止しました」とダイアログが表示されます
//----------------------------------------------------------------------

**Comment by DKAlpha** [comment]
記述した情報が誤っておりました。
ご迷惑をおかけいたします。

第4引数が同じ内容のものが２つあったため上の情報の方を修正いたしました。
引数が１つ多くなっていたためにコンバートに失敗したのだと思われます。
・修正前
ssbpToJson.exe c:\temp\anime.sspb yes yes yes yes yes C:\temp\out\
・修正後
ssbpToJson.exe "c:/temp/anime.sspb" yes yes yes yes "C:/temp/out/"

注意点としては、
・入力ファイルのパス、出力フォルダのパスに全角が含まれていると失敗する。
・出力フォルダのパスは最後/をつける
となります。
Windows上でbatファイルを作成してコンバートできる事を確認しましたのでこちらの変更をお元に再度お試しください。
よろしくお願いいたします。

**Comment by mintiatian** [comment]
失礼いたしました。
ご連絡いただいた通り引数を一つ減らして確認してみましたが
状況は変わりませんでした。
お手数ですが、よろしくお願いいたします。

//----------------------------------------------------------------------
ssbpToJson.exe "c:\temp\animetest.ssbp" yes yes yes yes "c:\temp\"
Ss5Converter To SSAJSON Version=1.0.2
convert start!
この後「ssbpToJson.exe は動作を停止しました」とダイアログが表示されます
//----------------------------------------------------------------------
・ssbpToJson.exe
DLしたZIPを解凍したフォルダに配置しています。
C:\Ss5ConverterToSSAJSON\

・animetest.ssbp
c:\tempにanimetest.ssbpのみ配置して確認しています。

**Comment by DKAlpha** [comment]
ご迷惑をおかけしております。
ログの方のバージョンを拝見して、Developに上げていたVer1.0.4を元にご説明を行っておりました。
Ver1.0.4では「カラーラベル、カラーブレンド、スプライトの頂点情報を出力する」が増えたため、Ver1.0.2から引数が変わった事により、コンバートに失敗したのだと思います。
Ver1.0.4をmasterブランチに反映いたしましたので、お手数ですが再度ダウンロードしてお試しいただければと思います。

**Comment by mintiatian** [comment]
お返事遅くなってしまい申し訳ありません。
新しいファイルをダウンロードを行い試してみましたが結果は変わりませんでした。
----------------------------------------------------------------------------------------
C:\temp>ssbpToJson.exe  "c:\temp\animetest.ssbp" yes yes yes yes "c:\temp"
Ss5Converter To SSAJSON Version=1.0.4
convert start!
----------------------------------------------------------------------------------------
とりあえず、Json化の自動化は諦め手動にて変換しプロジェクトへ
組み込むように対応いたしました。

**Comment by DKAlpha** [comment]
出力フォルダのパスの最後は/を入れて試してみていただけますでしょうか。
